config/routes.rb
Rails.application.routes.draw do

  resources :adults, :controller => "students", :type => "adult"
  resources :children, :controller => "students", :type => "child"
  resources :students
  resources :teachers do
    get 'classes', on: :member
  end

  resource :calendars, only: :show

  get '/all_classes', to: 'calendars#all_classes'

  resources :weekly_classes, only: :index

  resources :groups do
    get 'classes', on: :member
  end

  resources :students

  root 'students#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  include IceCube

  IceCube.compatibility = 12 # ?

  serialize :schedule, IceCube::Schedule

  has_many :students
  has_many :weekly_classes
  belongs_to :teacher
  #has_one :schedule

  delegate :hours_per_week, to: :schedule

  # TODO custom validator?
  validates :level, inclusion: { in: ::EFL_LEVELS }, allow_nil: true
  #validates :schedule, :no_overlap

  # schedule could also be another model with has_one relationship
  def schedules_cannot_overlap
    self.teacher.groups.any do |g|
      g.schedule.overlaps_with? self.schedule
    end
  end

  def self.all_classes
    
  end

  #def hours_per_week
    #return 0 unless self.schedule
    #schedule
  #end

  def name
    "Group #{id}"
  end

  def name_with_level
    "Group #{id} - #{level}"
  end

  def schedule
    # TODO delegate methods
    read_attribute(:schedule).extend Timetable
    # how to avoid reading if already loaded? memoize to inst var?
  end

  #def schedule
    #IceCube::Schedule.new() do |s|
      #s.add_recurrence_rule Rule.weekly.day(1, 2)
    #end
  #end

  def add_biweekly_schedule(day1, day2, time, duration = 60*60)
    # TODO dont i need duration?
    hour, minute = time.split(':')
    time = Time.now.change(hour: hour, minute: minute)
    #p time
    self.schedule = IceCube::Schedule.new(time, duration: duration) do |s|
                      s.add_recurrence_rule Rule.weekly.day(day1, day2)
                    end
    #pp self.schedule
    #save!
    self
  end

  def add_biweekly_schedule!(day1, day2, time, duration = 60*60)
    add_biweekly_schedule(day1, day2, time, duration)
    self.save
    self
  end

  class Klass
    @occurrence
  end

  def classes_between(start, finish)
    #self.schedule.occurrences_between Time.parse(start), Time.parse(finish)
    return [] unless self.schedule

    classes = self.schedule.occurrences_between start, finish

    # TODO don't know about this
    classes.each do |klass|
      klass.class.module_eval { attr_accessor :group} # m-patch IceCube::occurence?
      klass.group = self
    end

    return classes
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :classes]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def classes
    params[:start] && params[:end] or raise 'No start and end params'
    @classes = @group.classes_between Time.parse(params[:start]), 
                                      Time.parse(params[:end])
    pp @classes
    respond_to do |format|
      #format.html
      format.json { render 'classes' }
    end
    #render 'classes'
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:level)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @group.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h4>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :level, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :level, EFL_LEVELS, {include_blank: true}, {class: 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :teacher, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:teacher_id, Teacher.all, :id, :name, 
                              {include_blank: true}, 
                              {class: 'form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="page-header">
  <%= link_to new_group_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Group
  <% end %>
  <h1>Listing groups</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Level</th>
            <th>Name</th>
            <th>Teacher</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @groups) do |group| %>
            <td><%= group.level %></td>
            <td><%= group.name %></td>
            <td><%= group.teacher.name %></td>
            <%#TODO lonely op here%>
            <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="page-header">
  <%= link_to groups_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_group_path(@group), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show group</h1>
</div>

<dl class="dl-horizontal">
  <dt>Level:</dt>
  <dd><%= @group.level %></dd>

  <dt>Name:</dt>
  <dd><%= @group.name %></dd>

  <dt>Teacher:</dt>
  <dd><%= @group.teacher %></dd>

</dl>

<div class="calendar" id="group-calendar" data-group-id="<%= @group.id %>">
  
</div>