config/routes.rb
Rails.application.routes.draw do

  resources :adults, :controller => "students", :type => "adult"
  resources :children, :controller => "students", :type => "child"
  resources :students
  resources :teachers do
    get 'classes', on: :member
  end

  resource :calendars, only: :show

  get '/all_classes', to: 'calendars#all_classes'

  resources :weekly_classes, only: :index

  resources :groups do
    get 'classes', on: :member
  end

  resources :students

  root 'students#index'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  
  validates :color, uniqueness: true, numericality: false
  validates :name, uniqueness: true, presence: true, numericality: false

  def hours_per_week
    groups.map(&:hours_per_week).inject(:+)
  end

  # TODO how to dry up. Groups enumerator?
  def classes_between(*args)
    groups.flat_map { |g| g.classes_between(*args) }
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy, :classes]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  def classes
    params[:start] && params[:end] or raise 'No start and end params'
    @classes = @teacher.classes_between Time.parse(params[:start]), 
                                        Time.parse(params[:end])
    pp @classes
    respond_to do |format|
      #format.html
      format.json { render 'classes' }
    end
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :color)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @teacher.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h4>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :color, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :color, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="page-header">
  <%= link_to teachers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @teacher, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing teacher</h1>
</div>

<%= render 'form' %>

app/views/teachers/index.html.erb
<div class="page-header">
  <%= link_to new_teacher_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Teacher
  <% end %>
  <h1>Listing teachers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Color</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @teachers) do |teacher| %>
            <td><%= teacher.name %></td>
            <td><%= teacher.color %></td>
            <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/teachers/new.html.erb
<div class="page-header">
  <%= link_to teachers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New teacher</h1>
</div>

<%= render 'form' %>

app/views/teachers/show.html.erb
<div class="page-header">
  <%= link_to teachers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_teacher_path(@teacher), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show teacher</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @teacher.name %></dd>

  <dt>Color:</dt>
  <dd><%= @teacher.color %></dd>

</dl>


<div class="calendar" id="teacher-calendar" data-teacher-id="<%= @teacher.id %>">
  
</div>